export const supabaseUrl = "https://xhokkusekmoyxihuavrf.supabase.co";
export const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhob2trdXNla21veXhpaHVhdnJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2MzAzMjYsImV4cCI6MjA5MDIwNjMyNn0.Nep1keuuo1lG4ad-D-6dnB0JzHdJyx9eNZ0Qo7qElCA";
